version: '3'
services:
  db:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./my.cnf:/etc/mysql/my.cnf"
      - db_data:/var/lib/mysql
    ports:
      - "3333:3306"

volumes:
  db_data:
